-- Generated by scripts/gen-surface.py from the Tablet node files. Do not edit.
import Mathlib.Analysis.ConstantSpeed
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.Topology.MetricSpace.Lipschitz
import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.Calculus.Deriv.Shift
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
import Mathlib.MeasureTheory.Function.AbsolutelyContinuous
import Mathlib.MeasureTheory.Integral.IntervalIntegral.AbsolutelyContinuousFun
import Mathlib.MeasureTheory.Integral.IntervalIntegral.DerivIntegrable
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.Probability.StrongLaw
import Mathlib.Probability.ProductMeasure
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.MeasureTheory.Integral.Lebesgue.Basic
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Topology.MetricSpace.HausdorffDistance

/-!
# Advertised statements

The five main results of arXiv:2502.09871, "An atomic decomposition of one-dimensional
metric currents without boundary" (Chen, Goodman, Hernandez, Spector).

This module is the small, trusted surface a mathematical reader should audit against the
paper. It is self-contained: it imports Mathlib and nothing else, defines every notion the
five statements mention, and then states the five results, each body a deliberate `sorry`.
The proofs live in `Solution.lean`.

Comparator compiles this module and `Solution.lean` separately and in mutually invisible
environments, then requires the five compared theorems to have structurally identical types
and every constant reachable from those types to be identical in both. The definitions below
are therefore not a paraphrase of the proof development's definitions: they are the very same
declarations, at the very same root-namespace names, generated verbatim from the `Tablet`
node files by `scripts/gen-surface.py`. That script also takes the five statements from the
`Tablet` theorem sources and their docstrings below from `scripts/statement_docs/`. Running it
with `--check` fails if any of this has drifted from the proof development.

The definitions are:

* `Curve E` -- a Lipschitz curve in `E`, parametrized by arc length on `[0, len]` and
  clamped to a total function `ℝ → E` outside that interval.
* `Form1 E` -- a metric `1`-form `ω = (f, π) ∈ 𝒟¹(E)`, a bounded Lipschitz `f` paired with
  a Lipschitz `π`.
* `IsAdmissible T μ` -- `μ` dominates the functional `T` in the sense of the mass-measure
  inequality; `massOfFunctional T` -- the mass `𝕄(T)`, the infimum of `μ(E)` over admissible `μ`.
* `MetricCurrent1 E` -- a metric `1`-current: a functional on `Form1 E` that is multilinear,
  continuous and local, with finite mass.
* `BoundaryZero T` -- the current `T` has vanishing boundary, `∂T = 0`.
* `curveCurrent γ` -- the current `[[γ]]` carried by the curve `γ`; `curveMeasure γ` -- the
  measure `‖γ‖` carried by `γ`; `morreyNorm μ` -- the Morrey norm `sup_{x, r} μ(B(x, r)) / r`.
* `IsGeodesicOn`, `IsGeodesicResolution`, `IsPiecewiseGeodesicWith γ k`, `IsPiecewiseGeodesic γ`,
  `IsClosedCurve γ` -- `γ` is a concatenation of (at most `k`) geodesics, and is closed.
* `GeodesicPairing E` -- a choice of geodesic between each pair of points, i.e. the witness
  that `E` is a geodesic space.
* `ThetaL l`, `curveRestrict`, `curveRestrictTot`, `CurveMeasurableSpace`, `PSFamily T` --
  the Paolini--Stepanov family of curves representing `T` together with its rescaled measures
  `eta l`, and the σ-algebra on `Curve E` with respect to which those measures are taken.
* `psi m Q ε C γ` -- the test functional `ψ_{m,Q,ε,C}` of Appendix A.

Two results the paper cites rather than proves appear as explicit hypotheses rather than as
axioms, so that nothing here is assumed silently:

* `MassSupFormulaStatement E` -- Ambrosio--Kirchheim Proposition 2.7, the hard direction of
  the mass supremum formula. Used by Theorem 1.1 and Theorem 4.4 only.
* `PaoliniStepanovExistsStatement E` -- Paolini--Stepanov Theorem 3.1 with Proposition 4.2,
  existence of a mass-realizing family of curves. Used by Theorem 1.1 and Theorem 4.4 only.

Corollaries 2.6, 3.2 and A.6 below are unconditional.
-/

section
open MeasureTheory Set

/-- A Lipschitz curve in `E`, parametrized by arc length on `[0, len]`, normalized to a
globally-defined function on all of `ℝ` by clamping outside `[0, len]`. -/
structure Curve (E : Type*) [MetricSpace E] where
  len : ℝ
  len_nonneg : 0 ≤ len
  toFun : ℝ → E
  clamped : ∀ t : ℝ, toFun t = toFun (min len (max 0 t))
  unitSpeed : HasUnitSpeedOn toFun (Set.Icc 0 len)
end

section
open scoped NNReal

/-- A metric $1$-form $\omega = (f,\pi) \in \mathcal{D}^1(E)$: a bounded Lipschitz function `f`
paired with a Lipschitz function `pi`. The bound on `f` and the Lipschitz constants of both `f`
and `pi` are carried as explicit fields, so that `‖f‖_∞` and `Lip(pi)` are named data rather than
constructed as a suprema at each use site. -/
structure Form1 (E : Type*) [MetricSpace E] where
  f : E → ℝ
  fBound : ℝ≥0
  f_bounded : ∀ x : E, |f x| ≤ (fBound : ℝ)
  fLip : ℝ≥0
  f_lipschitz : LipschitzWith fLip f
  pi : E → ℝ
  piLip : ℝ≥0
  pi_lipschitz : LipschitzWith piLip pi
end

section
open MeasureTheory ENNReal

/-- A finite Borel measure `μ` on `E` is admissible for a functional `T : Form1 E → ℝ` when it
dominates `T` in the sense of paper eq. (massmeasure), paper.tex line 1099 (specialized to `k = 1`):
`|T(f,π)| ≤ Lip(π) ∫_E |f| dμ` for every `1`-form `ω = (f,π)`. -/
def IsAdmissible {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    (T : Form1 E → ℝ) (μ : Measure E) : Prop :=
  IsFiniteMeasure μ ∧
    ∀ ω : Form1 E, ENNReal.ofReal |T ω| ≤ (ω.piLip : ℝ≥0∞) * ∫⁻ x, ENNReal.ofReal |ω.f x| ∂μ
end

section
open MeasureTheory ENNReal

/-- The mass `𝕄(T)` of a functional `T : Form1 E → ℝ` (paper.tex line 1100), defined as the
infimum of the total mass `μ(E)` over admissible measures `μ` (\noderef{IsAdmissible}), rather than
via the minimum admissible measure (whose existence is Ambrosio–Kirchheim's theorem, and which this
tablet does not construct). When some admissible measure exists this agrees with the paper's
`μ_T(E)` for the (existing) minimal admissible measure `μ_T`, since the infimum of total masses over
the admissible class is achieved exactly at any pointwise-minimal element of that class. -/
noncomputable def massOfFunctional {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    (T : Form1 E → ℝ) : ℝ≥0∞ :=
  ⨅ μ : { μ : Measure E // IsAdmissible T μ }, (μ.1 Set.univ)
end

section
open MeasureTheory ENNReal Filter Topology
open scoped NNReal

/-- A metric $1$-current on `E` (Ambrosio–Kirchheim `Def. 3.1`, specialized to `k = 1`,
`\mathcal{M}_1(E)`, paper.tex line 1101): a functional `toFun : Form1 E → ℝ` that is bilinear in
`(f,π)` (`add_f`/`smul_f`/`add_pi`/`smul_pi`), continuous with respect to pointwise convergence of
`π` with uniformly bounded Lipschitz constants (`continuous_pi`, paper.tex line 1393), local
(`locality`), and of finite mass (`finiteMass`, the specialization of the mass-measure inequality
paper.tex line 1099 to a genuine current, `massOfFunctional toFun ≠ ⊤`). Continuity with respect to
pointwise convergence of `f` is deliberately *not* an axiom here: paper.tex line 1393 derives it
from `finiteMass` together with Lebesgue's dominated convergence theorem, so axiomatizing it would
strengthen the definition beyond what the paper justifies. -/
structure MetricCurrent1 (E : Type*) [MetricSpace E] [MeasurableSpace E] [BorelSpace E] where
  toFun : Form1 E → ℝ
  add_f : ∀ ω1 ω2 ω12 : Form1 E, ω1.pi = ω2.pi → ω1.pi = ω12.pi →
      (∀ x, ω12.f x = ω1.f x + ω2.f x) → toFun ω12 = toFun ω1 + toFun ω2
  smul_f : ∀ (ω ωc : Form1 E) (c : ℝ), ωc.pi = ω.pi →
      (∀ x, ωc.f x = c * ω.f x) → toFun ωc = c * toFun ω
  add_pi : ∀ ω1 ω2 ω12 : Form1 E, ω1.f = ω2.f → ω1.f = ω12.f →
      (∀ x, ω12.pi x = ω1.pi x + ω2.pi x) → toFun ω12 = toFun ω1 + toFun ω2
  smul_pi : ∀ (ω ωc : Form1 E) (c : ℝ), ωc.f = ω.f →
      (∀ x, ωc.pi x = c * ω.pi x) → toFun ωc = c * toFun ω
  continuous_pi : ∀ (f : E → ℝ) (bF : ℝ≥0) (hbF : ∀ x, |f x| ≤ (bF : ℝ)) (LF : ℝ≥0)
      (hLF : LipschitzWith LF f) (π : E → ℝ) (Lπ : ℝ≥0) (hLπ : LipschitzWith Lπ π)
      (πs : ℕ → E → ℝ) (Ls : ℕ → ℝ≥0) (hLs : ∀ n, LipschitzWith (Ls n) (πs n))
      (L0 : ℝ≥0) (hbound : ∀ n, Ls n ≤ L0)
      (hconv : ∀ x, Tendsto (fun n => πs n x) atTop (nhds (π x))),
      Tendsto (fun n => toFun ⟨f, bF, hbF, LF, hLF, πs n, Ls n, hLs n⟩) atTop
        (nhds (toFun ⟨f, bF, hbF, LF, hLF, π, Lπ, hLπ⟩))
  locality : ∀ ω : Form1 E,
      (∃ U : Set E, IsOpen U ∧ {x | ω.f x ≠ 0} ⊆ U ∧ ∃ c : ℝ, ∀ x ∈ U, ω.pi x = c) →
      toFun ω = 0
  finiteMass : massOfFunctional toFun ≠ (⊤ : ℝ≥0∞)
end

section
open scoped NNReal

/-- The boundary vanishing condition for a functional `T : Form1 E → ℝ` (paper.tex lines
1112–1120): `∂T = 0`, i.e. `T(dω) = 0` for every `ω ∈ \mathcal{D}^0(E)`, specialized to `k = 1` so
that `dω = (1,f)` for `ω = f` ranging over bounded Lipschitz functions. Built from `Form1` by
pairing the constant function `1` (bounded by `1`, `0`-Lipschitz) with `f`. -/
def BoundaryZero {E : Type*} [MetricSpace E] (T : Form1 E → ℝ) : Prop :=
  ∀ (f : E → ℝ) (b : ℝ≥0) (_hb : ∀ x, |f x| ≤ (b : ℝ)) (L : ℝ≥0) (hL : LipschitzWith L f),
    T ⟨fun _ => (1 : ℝ), 1, fun x => by simp, 0,
        by simp [LipschitzWith.const (α := E) (1 : ℝ)], f, L, hL⟩ = 0
end

section

/-- The current $[[\gamma]](\omega)$ of a curve $\gamma$ against a $1$-form $\omega = (f,\pi)$
(paper eq. (4.3)): the Lebesgue integral $\int_0^{\length(\gamma)} f(\gamma(t)) \cdot
\deriv(\pi \circ \gamma)(t)\,dt$, which computes the paper's Riemann-Stieltjes integral because
$\pi \circ \gamma$ is globally Lipschitz, hence absolutely continuous. -/
noncomputable def curveCurrent {E : Type*} [MetricSpace E] (γ : Curve E) (ω : Form1 E) : ℝ :=
  ∫ t in (0:ℝ)..γ.len, ω.f (γ.toFun t) * deriv (ω.pi ∘ γ.toFun) t
end

section
open MeasureTheory Set

/-- The Borel measure `μ_γ` on `E` induced by a curve `γ`: the pushforward, under `γ`, of
Lebesgue measure restricted to `[0, γ.len]` (paper eq. (2.1)). -/
noncomputable def curveMeasure {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    (γ : Curve E) : Measure E :=
  Measure.map γ.toFun (volume.restrict (Set.Icc 0 γ.len))
end

section
open MeasureTheory Set ENNReal

/-- The Morrey norm of a Borel measure `μ` on `E` (paper eq. (2.3)). -/
noncomputable def morreyNorm {E : Type*} [MetricSpace E] [MeasurableSpace E]
    (μ : Measure E) : ℝ≥0∞ :=
  ⨆ x : E, ⨆ r : ℝ, ⨆ _ : 0 < r, μ (Metric.closedBall x r) / ENNReal.ofReal r
end

section
open Set

/-- `γ` is a geodesic on the subinterval `[a,b]` of its domain: `γ` is an isometric embedding of
`[a,b]` into `E` there. -/
def IsGeodesicOn {E : Type*} [MetricSpace E] (γ : Curve E) (a b : ℝ) : Prop :=
  ∀ s ∈ Set.Icc a b, ∀ t ∈ Set.Icc a b, dist (γ.toFun s) (γ.toFun t) = |s - t|
end

section
open Set

/-- `s : ℕ → ℝ` is a resolution of `γ` into `k` geodesic edges: `s` is monotone on `{0,…,k}`,
runs from `0` to `γ.len`, and each consecutive pair of values bounds a geodesic edge of `γ`.
Consecutive values of `s` are allowed to repeat (a degenerate, zero-length edge). -/
def IsGeodesicResolution {E : Type*} [MetricSpace E] (γ : Curve E) (k : ℕ) (s : ℕ → ℝ) : Prop :=
  MonotoneOn s (Set.Icc 0 k) ∧ s 0 = 0 ∧ s k = γ.len ∧
    ∀ i < k, IsGeodesicOn γ (s i) (s (i + 1))
end

section

/-- `γ` admits a resolution into `k` geodesic edges (possibly with some degenerate, zero-length
edges): `γ` is a piecewise-geodesic curve expressible with `k` pieces. -/
def IsPiecewiseGeodesicWith {E : Type*} [MetricSpace E] (γ : Curve E) (k : ℕ) : Prop :=
  ∃ s : ℕ → ℝ, IsGeodesicResolution γ k s
end

section

/-- `γ` is a piecewise-geodesic curve: it admits a resolution into `k` geodesic edges for some `k`. -/
def IsPiecewiseGeodesic {E : Type*} [MetricSpace E] (γ : Curve E) : Prop :=
  ∃ k : ℕ, IsPiecewiseGeodesicWith γ k
end

section

/-- `γ` is a closed curve: its two endpoints coincide. -/
def IsClosedCurve {E : Type*} [MetricSpace E] (γ : Curve E) : Prop :=
  γ.toFun γ.len = γ.toFun 0
end

section
open Set

/-- A choice, for every ordered pair `(x,y)` of points of `E`, of a geodesic `G x y` of length
`dist x y` from `x` to `y`, such that `G y x` is the reversal of `G x y` (paper eq. (2.5) and the
surrounding discussion, lines 517--526). The paper notes that constructing such a family
simultaneously for all pairs may require the axiom of choice; accordingly this is packaged as a
hypothesis carrier rather than derived from a bare geodesic-space assumption on `E`. -/
structure GeodesicPairing (E : Type*) [MetricSpace E] where
  G : E → E → Curve E
  len_eq : ∀ x y : E, (G x y).len = dist x y
  start_eq : ∀ x y : E, (G x y).toFun 0 = x
  end_eq : ∀ x y : E, (G x y).toFun (G x y).len = y
  isGeodesic : ∀ x y : E, IsGeodesicOn (G x y) 0 (G x y).len
  reversal : ∀ x y : E, ∀ t ∈ Set.Icc (0:ℝ) (dist x y), (G y x).toFun t = (G x y).toFun (dist x y - t)
end

section
open MeasureTheory ENNReal

/-- Ambrosio--Kirchheim `[AK, Prop. 2.7]` (paper.tex ~1497--1501), hard direction only, indexed
over finite families: if every finite family `ω : Fin n → Form1 E` with `Lip(π_p) ≤ 1` for all `p`
and `∑_p |f_p(x)| ≤ 1` for every `x` has `∑_p |T(ω p)| ≤ c`, then `massOfFunctional T.toFun ≤
ENNReal.ofReal c`. The reverse direction `sup ≤ massOfFunctional T.toFun` is free from the
definition of `massOfFunctional` as an infimum and is proved inline at each use site rather than
cited here. `[CompleteSpace E] [TopologicalSpace.SeparableSpace E]` discharge the paper's standing
ambient hypothesis on `E` (paper.tex line 1096) under which AK Prop. 2.7 is invoked; geodesy is
deliberately not assumed, since Prop. 2.7 is a statement about `M₁(E)` with no reference to
geodesics.

This node is an external literature citation, not a tablet proof. It is therefore recorded as a
`Prop`-valued statement about `E` rather than as a theorem with an unproved body: the nodes that
consume it (`\noderef{BBAssertion}` and, through it, `\noderef{ApproximationMetric}`) take
`MassSupFormulaStatement E` as an explicit hypothesis. The citation is thereby discharged by the
caller, and the tablet's own theorems depend on no axioms beyond `propext`, `Classical.choice`
and `Quot.sound`. -/
def MassSupFormulaStatement (E : Type*) [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    [CompleteSpace E] [TopologicalSpace.SeparableSpace E] : Prop :=
  ∀ (T : MetricCurrent1 E) (c : ℝ), 0 ≤ c →
    (∀ (n : ℕ) (ω : Fin n → Form1 E),
      (∀ p, (ω p).piLip ≤ 1) →
      (∀ x : E, ∑ p, |(ω p).f x| ≤ 1) →
      ∑ p, |T.toFun (ω p)| ≤ c) →
    massOfFunctional T.toFun ≤ ENNReal.ofReal c
end

section
open ENNReal

/-- The set `Θ_l(E)` of curves whose current has mass exactly `l` (paper.tex line 1178). -/
def ThetaL {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E] (l : ℕ) :
    Set (Curve E) :=
  { γ | massOfFunctional (curveCurrent γ) = (l : ℝ≥0∞) }
end

section
open Set

/-- The restriction $\gamma|_{[a,b]}$ of a curve to a subinterval $[a,b] \subseteq [0,\length(\gamma)]$,
reparametrized to start at $0$ (paper line 449/459): $\gamma|_{[a,b]}(u) = \gamma(a+u)$ for
$u \in [0,b-a]$, extended by clamping outside $[0,b-a]$ as usual for a `Curve`. -/
noncomputable def curveRestrict {E : Type*} [MetricSpace E] (γ : Curve E) (a b : ℝ)
    (ha : 0 ≤ a) (hab : a ≤ b) (hb : b ≤ γ.len) : Curve E where
  len := b - a
  len_nonneg := by linarith
  toFun := fun u => γ.toFun (a + min (b - a) (max 0 u))
  clamped := by
    intro u
    set v : ℝ := min (b - a) (max 0 u) with hv_def
    have hv0 : (0:ℝ) ≤ v := le_min (by linarith) (le_max_left _ _)
    have hv1 : v ≤ b - a := min_le_left _ _
    have step1 : max (0:ℝ) v = v := le_antisymm (max_le hv0 le_rfl) (le_max_right _ _)
    have step2 : min (b - a) v = v := le_antisymm (min_le_right _ _) (le_min hv1 le_rfl)
    show γ.toFun (a + v) = γ.toFun (a + min (b - a) (max 0 v))
    rw [step1, step2]
  unitSpeed := by
    have hEq : Set.EqOn (fun u => γ.toFun (a + min (b - a) (max 0 u)))
        (fun u => γ.toFun (a + u)) (Set.Icc 0 (b - a)) := by
      intro u hu
      obtain ⟨hu0, hu1⟩ := hu
      simp only []
      rw [max_eq_right hu0, min_eq_right hu1]
    intro x hx y hy
    rw [eVariationOn.eq_of_eqOn (hEq.mono Set.inter_subset_left)]
    have hmono : MonotoneOn (fun u : ℝ => a + u) (Set.Icc 0 (b - a)) := by
      intro p _ q _ hpq; simpa using hpq
    have key := eVariationOn.comp_inter_Icc_eq_of_monotoneOn γ.toFun (fun u : ℝ => a + u) hmono hx hy
    have himg : (fun u : ℝ => a + u) '' Set.Icc 0 (b - a) = Set.Icc a b := by
      ext z
      constructor
      · rintro ⟨u, ⟨hu0, hu1⟩, rfl⟩; constructor <;> simp <;> linarith
      · rintro ⟨hz0, hz1⟩; exact ⟨z - a, ⟨by linarith, by linarith⟩, by ring⟩
    have hfun : (fun u => γ.toFun (a + u)) = γ.toFun ∘ (fun u : ℝ => a + u) := rfl
    rw [hfun, key, himg]
    obtain ⟨hx0, hx1⟩ := hx
    obtain ⟨hy0, hy1⟩ := hy
    rcases le_total x y with hxy | hyx
    · have hset : Set.Icc a b ∩ Set.Icc (a + x) (a + y)
          = Set.Icc 0 γ.len ∩ Set.Icc (a + x) (a + y) := by
        ext z
        simp only [Set.mem_inter_iff, Set.mem_Icc]
        constructor
        · rintro ⟨⟨h1, h2⟩, h3, h4⟩; exact ⟨⟨by linarith, by linarith⟩, h3, h4⟩
        · rintro ⟨⟨h1, h2⟩, h3, h4⟩; exact ⟨⟨by linarith, by linarith⟩, h3, h4⟩
      rw [hset]
      have := γ.unitSpeed (x := a + x) ⟨by linarith, by linarith⟩
        (y := a + y) ⟨by linarith, by linarith⟩
      rw [this]
      congr 1
      push_cast
      ring
    · rw [eVariationOn.subsingleton, ENNReal.ofReal_of_nonpos (by push_cast; nlinarith)]
      exact (Set.subsingleton_Icc_of_ge (by linarith)).anti Set.inter_subset_right
end

section

/-- The total, clamped restriction of a curve to `[a,b]`: agrees with `curveRestrict` whenever
`0 ≤ a ≤ b ≤ γ.len` (see `CurveRestrictTotAgrees`), and is otherwise a junk-but-total value
obtained by first clamping `a,b` into `[0, γ.len]` (and clamping `b` above `a`) before restricting.
This total version is what measure-theoretic statements (which only get `a,b` satisfying the
side conditions almost everywhere) must use instead of the proof-carrying `curveRestrict`. -/
noncomputable def curveRestrictTot {E : Type*} [MetricSpace E] (γ : Curve E) (a b : ℝ) :
    Curve E :=
  curveRestrict γ (min (max a 0) γ.len) (max (min (max a 0) γ.len) (min (max b 0) γ.len))
    (le_min (le_max_right _ _) γ.len_nonneg) (le_max_left _ _)
    (max_le (min_le_right _ _) (min_le_right _ _))
end

section

/-- The evaluation `σ`-algebra on `Curve E`: the coarsest `MeasurableSpace` structure making the
evaluation map `γ ↦ (γ.len, γ.toFun)` measurable, i.e. the `comap` of the product `MeasurableSpace`
on `ℝ × (ℝ → E)` along that map. This is the structure with respect to which every measure-theoretic
statement about curves in this tablet (the Paolini–Stepanov family, its marginals, mass) is stated. -/
instance CurveMeasurableSpace {E : Type*} [MetricSpace E] [MeasurableSpace E] :
    MeasurableSpace (Curve E) :=
  MeasurableSpace.comap (fun γ => (γ.len, γ.toFun)) inferInstance
end

section
open MeasureTheory ENNReal

/-- The Paolini–Stepanov by-product family for a functional `T : Form1 E → ℝ`: a sequence of
finite Borel measures `η_l` on `Θ(E)` (`l ∈ ℕ`), one for each integer length, together with the
identities eq. (4.6) (`weakLength`), eq. (4.8) (`lengthExactly`), eq. (4.7) (`massMarginal`), and
Lemma A.5 (`marginal`) that Paolini–Stepanov's construction produces as by-products
(paper.tex lines 1178–1216). -/
structure PSFamily {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    (T : Form1 E → ℝ) where
  /-- `η_l`, a Borel measure on `Θ(E)` for each `l ∈ ℕ`. -/
  eta : ℕ → Measure (Curve E)
  /-- Each `η_l` is a finite measure. -/
  finite : ∀ l : ℕ, IsFiniteMeasure (eta l)
  /-- `η_l` is supported on `Θ_l(E)` for `l ≥ 1`. -/
  supported : ∀ l : ℕ, 1 ≤ l → eta l ((ThetaL l : Set (Curve E))ᶜ) = 0
  /-- Eq.~(4.8): `𝕄([[γ]]) = length(γ) = l` for `η_l`-a.e.\ `γ`, `l ≥ 1`. -/
  lengthExactly : ∀ l : ℕ, 1 ≤ l → ∀ᵐ γ ∂(eta l), γ.len = (l : ℝ)
  /-- Eq.~(4.6): `T(ω) = (1/l) ∫ [[γ]](ω) dη_l(γ)` for every `1`-form `ω`, `l ≥ 1`. -/
  weakLength : ∀ l : ℕ, 1 ≤ l → ∀ ω : Form1 E,
    T ω = (l : ℝ)⁻¹ * ∫ γ, curveCurrent γ ω ∂(eta l)
  /-- The mass measure `μ_T` of `T` (paper.tex line 1100), carried as data alongside its
  characterization via `η_l`'s beginning/ending marginals. -/
  massMeasure : Measure E
  massMeasure_finite : IsFiniteMeasure massMeasure
  /-- Eq.~(4.7): for every nonnegative measurable `φ : E → ℝ≥0∞` and `l ≥ 1`, `∫ φ dμ_T` equals
  both the `η_l`-average of `φ` at the curve's start and at its end. -/
  massMarginal : ∀ l : ℕ, 1 ≤ l → ∀ φ : E → ℝ≥0∞, Measurable φ →
    (∫⁻ x, φ x ∂massMeasure = ∫⁻ γ, φ (γ.toFun 0) ∂(eta l))
      ∧ (∫⁻ x, φ x ∂massMeasure = ∫⁻ γ, φ (γ.toFun γ.len) ∂(eta l))
  /-- Lemma A.5 (paper.tex line 1860): the marginal of `η_l` under restriction to the `j`-th unit
  subcurve, `j ∈ {1,…,l}`, coincides with `η_1`, stated for nonnegative measurable `h`. -/
  marginal : ∀ l j : ℕ, 1 ≤ j → j ≤ l → ∀ h : Curve E → ℝ≥0∞, Measurable h →
    ∫⁻ γ, h (curveRestrictTot γ ((j : ℝ) - 1) (j : ℝ)) ∂(eta l) = ∫⁻ γ, h γ ∂(eta 1)
end

section
open MeasureTheory ENNReal

/-- Paolini--Stepanov `[PS, Thm 3.1]` + `[PS, Prop 4.2]` (paper.tex 1183–1216): for a metric
`1`-current `T` on a complete separable `E` with `∂T = 0` (`BoundaryZero`) and `T ≠ 0`, there is a
Paolini–Stepanov family `F` for `T.toFun` (`PSFamily`) whose mass measure realizes the total mass
of `T` (paper.tex 1192, `M(T) = η_1(Θ_1(E))`, combined with `massOfFunctional`'s own
minimum-realizes-infimum equivalence).

This node is an external literature citation, not a tablet proof. It is therefore recorded as a
`Prop`-valued statement about `E` rather than as a theorem with an unproved body: the nodes that
consume it (`\noderef{BBAssertion}` and, through it, `\noderef{ApproximationMetric}`) take
`PaoliniStepanovExistsStatement E` as an explicit hypothesis. The citation is thereby discharged
by the caller, and the tablet's own theorems depend on no axioms beyond `propext`,
`Classical.choice` and `Quot.sound`. -/
def PaoliniStepanovExistsStatement (E : Type*) [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    [CompleteSpace E] [TopologicalSpace.SeparableSpace E] : Prop :=
  ∀ (T : MetricCurrent1 E), T.toFun ≠ 0 → BoundaryZero T.toFun →
    ∃ F : PSFamily T.toFun, F.massMeasure Set.univ = massOfFunctional T.toFun
end

section

/-- `ψ_{m,Q,ε,C}(γ)`, paper Lemma A.2 display (paper.tex line 1718), with `s_i = i·γ.len/m`. -/
noncomputable def psi {E : Type*} [MetricSpace E] (m : ℕ) (Q : Finset E) (ε C : ℝ)
    (γ : Curve E) : ℝ :=
  C * (∑ i ∈ Finset.Icc 1 m,
        min (2 * C * γ.len / m)
          (2 * ε + 2 * C * (Metric.infDist (γ.toFun (i * γ.len / m)) (Q : Set E)
                          + Metric.infDist (γ.toFun ((i - 1) * γ.len / m)) (Q : Set E))))
    + 2 * C ^ 2 * γ.len ^ 2 / m
end

open Set Filter Finset MeasureTheory ENNReal

namespace AtomicDecomposition

/-- **Theorem 1.1** (`ApproximationMetric`). Every boundaryless `1`-dimensional metric current
`T` on a complete, separable, geodesic metric space `E` is a limit of finite nonnegative
combinations of closed piecewise-geodesic curves, with total weight at most `(1 + ε)` times
the mass of `T` and each curve's Morrey norm at most `2088 / ε²`.

The paper's universal constant `C` is pinned here to the numeral `2088 = 4 · 522`. Because
the paper quantifies `C` universally, outside the data, pinning a concrete value is at least
as strong as the paper's existential form.

`[Nonempty E]` is needed because the conclusion asserts a total function `γ : ℕ → ℕ → Curve E`
while `Curve E` is uninhabited exactly when `E` is, and no other hypothesis forces `E`
nonempty (this statement, unlike Theorem 4.4, carries no `T ≠ 0` hypothesis). -/
theorem ApproximationMetric {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    [CompleteSpace E] [TopologicalSpace.SeparableSpace E] [Nonempty E]
    (hAK : MassSupFormulaStatement E) (hPS : PaoliniStepanovExistsStatement E)
    (GP : GeodesicPairing E)
    (T : MetricCurrent1 E) (hbdry : BoundaryZero T.toFun)
    (ε : ℝ) (hε0 : 0 < ε) (hε1 : ε ≤ 1) :
    ∃ (γ : ℕ → ℕ → Curve E) (lam : ℕ → ℕ → ℝ),
      (∀ n : ℕ, ∀ i < n, 0 ≤ lam n i) ∧
      (∀ n : ℕ, ∀ i < n, IsClosedCurve (γ n i)) ∧
      (∀ n : ℕ, ∀ i < n, IsPiecewiseGeodesic (γ n i)) ∧
      (∀ ω : Form1 E, Tendsto (fun n : ℕ =>
          ∑ i ∈ Finset.range n, lam n i * (curveCurrent (γ n i) ω / (γ n i).len))
        atTop (nhds (T.toFun ω))) ∧
      (∀ n : ℕ, ∑ i ∈ Finset.range n, |lam n i|
          ≤ (1 + ε) * (massOfFunctional T.toFun).toReal) ∧
      (∀ n : ℕ, ∀ i < n,
          morreyNorm (curveMeasure (γ n i)) ≤ ENNReal.ofReal (2088 / ε ^ 2))
    := by
  sorry

/-- **Theorem 4.4** (`BBAssertion`). A nonzero boundaryless `1`-dimensional metric current `T`
on a complete, separable, geodesic metric space admits a normalized decomposition along a
doubly-indexed family of closed piecewise-geodesic curves `ghat l i` of length at most `2l`,
with `𝕄([[ghat l i]]) ≤ len (ghat l i)`, such that the normalized sums converge to `T ω` for
every `1`-form `ω` and the mass and length averages both tend to `1`. -/
theorem BBAssertion {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    [CompleteSpace E] [TopologicalSpace.SeparableSpace E] [Nonempty E]
    (hAK : MassSupFormulaStatement E) (hPS : PaoliniStepanovExistsStatement E)
    (GP : GeodesicPairing E)
    (T : MetricCurrent1 E) (hT0 : T.toFun ≠ 0) (hbdry : BoundaryZero T.toFun) :
    ∃ (n : ℕ → ℕ) (ghat : ℕ → ℕ → Curve E),
      (∀ l : ℕ, 0 < n l) ∧ Tendsto n atTop atTop ∧
      (∀ l : ℕ, 1 ≤ l → ∀ i < n l, IsClosedCurve (ghat l i)) ∧
      (∀ l : ℕ, 1 ≤ l → ∀ i < n l, IsPiecewiseGeodesic (ghat l i)) ∧
      (∀ l : ℕ, 1 ≤ l → ∀ i < n l,
        massOfFunctional (curveCurrent (ghat l i)) ≤ ENNReal.ofReal (ghat l i).len) ∧
      (∀ l : ℕ, 1 ≤ l → ∀ i < n l, (ghat l i).len ≤ 2 * (l : ℝ)) ∧
      (∀ ω : Form1 E, Tendsto (fun l : ℕ =>
          (massOfFunctional T.toFun).toReal / ((n l : ℝ) * l) *
            ∑ i ∈ Finset.range (n l), curveCurrent (ghat l i) ω)
          atTop (nhds (T.toFun ω))) ∧
      (Tendsto (fun l : ℕ => (1 / ((n l : ℝ) * l)) *
          ∑ i ∈ Finset.range (n l), (massOfFunctional (curveCurrent (ghat l i))).toReal)
        atTop (nhds 1)) ∧
      (Tendsto (fun l : ℕ => (1 / ((n l : ℝ) * l)) *
          ∑ i ∈ Finset.range (n l), (ghat l i).len)
        atTop (nhds 1))
    := by
  sorry

/-- **Corollary 3.2** (`SurgeryEta`). A closed piecewise-geodesic curve `γ` splits into
finitely many closed piecewise-geodesic curves carrying the same current, of total length at
most `(1 + η)` times the length of `γ`, each of Morrey norm at most `522 / η²`.

The paper's absolute constant `c` in the prescription `ε = cη`, `n = ⌈ε⁻²⌉` is pinned to
`1/15`, which is sharp at `η = 1` for this argument, and the universal constant `C'` is
pinned to the numeral `522`. -/
theorem SurgeryEta {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    (GP : GeodesicPairing E) (γ : Curve E) (η : ℝ)
    (hη0 : 0 < η) (hη1 : η ≤ 1)
    (hclosed : IsClosedCurve γ) (hpg : IsPiecewiseGeodesic γ) :
    ∃ (N : ℕ) (g : Fin N → Curve E), 0 < N ∧
      (∀ j, IsClosedCurve (g j)) ∧ (∀ j, IsPiecewiseGeodesic (g j)) ∧
      (∀ ω : Form1 E, curveCurrent γ ω = ∑ j, curveCurrent (g j) ω) ∧
      (∑ j, (g j).len) ≤ (1 + η) * γ.len ∧
      (∀ j, morreyNorm (curveMeasure (g j)) ≤ ENNReal.ofReal (522 / η ^ 2))
    := by
  sorry

/-- **Corollary 2.6** (`C1SmallBall`). A concatenation of at most `k` geodesics has Morrey
norm at most `2k`.

Stated for an arbitrary metric space, since the proof uses neither completeness, nor
separability, nor ambient geodesy. -/
theorem C1SmallBall {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    (γ : Curve E) (k : ℕ) (hpw : IsPiecewiseGeodesicWith γ k) :
    morreyNorm (curveMeasure γ) ≤ 2 * (k : ℝ≥0∞)
    := by
  sorry

/-- **Corollary A.6** (`EtaRepeats`), the `ψ` display: the rescaling identity relating the
measures `eta l` and `eta 1` of a Paolini--Stepanov family, tested against `ψ`.

The companion `ψ̃` display of the same corollary is formalized separately, as
`EtaRepeatsTilde` in the proof development, and is not part of this compared surface. -/
theorem EtaRepeats {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]
    (T : Form1 E → ℝ) (F : PSFamily T)
    (m : ℕ) (hm : 0 < m) (Q : Finset E) (ε C : ℝ) (hε : 0 < ε) (hC : 0 < C)
    (l : ℕ) (hl : 0 < l) :
    ∫ γ, (l : ℝ)⁻¹ * psi (m * l) Q ε C γ ∂(F.eta l)
      = ∫ γ, psi m Q ε C γ ∂(F.eta 1)
    := by
  sorry

end AtomicDecomposition
