#!/usr/bin/env python3
"""Generate Challenge.lean and Solution.lean from the Tablet node files.

Comparator compiles Challenge.lean and Solution.lean separately, in environments that
cannot see each other, and then demands that the five compared theorems have structurally
identical types *and* that every constant reachable from those types be identical in both.
Challenge.lean may import only Mathlib, so it cannot reach the Tablet definitions; it has to
carry its own copy of them. This script produces that copy verbatim from the Tablet sources,
so the two environments agree by construction rather than by vigilance.

  ./scripts/gen-surface.py            rewrite Challenge.lean and Solution.lean
  ./scripts/gen-surface.py --check    fail if either file is out of date
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TABLET = ROOT / "Tablet"
# Per-theorem docstrings for the advertised surface: each maps a declaration to its result
# in the paper and records what the formalization pins down (the numerals standing in for
# the paper's universal constants, why `[Nonempty E]` is needed, what is out of scope).
# These are written for the mathematical reader auditing Challenge.lean, and are
# deliberately not the Tablet nodes' own docstrings, which are internal and cite node names.
STATEMENT_DOCS = ROOT / "scripts/statement_docs"

# Mathlib modules Challenge.lean needs: Tablet/Preamble.lean's list, plus the extra imports
# carried by the individual node files below (Lebesgue/Bochner integrals, Hausdorff distance).
CHALLENGE_IMPORTS = [
    "Mathlib.Analysis.ConstantSpeed",
    "Mathlib.MeasureTheory.Measure.Lebesgue.Basic",
    "Mathlib.Topology.MetricSpace.Lipschitz",
    "Mathlib.MeasureTheory.Constructions.BorelSpace.Metric",
    "Mathlib.Analysis.Calculus.Deriv.Basic",
    "Mathlib.Analysis.Calculus.Deriv.Shift",
    "Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic",
    "Mathlib.MeasureTheory.Function.AbsolutelyContinuous",
    "Mathlib.MeasureTheory.Integral.IntervalIntegral.AbsolutelyContinuousFun",
    "Mathlib.MeasureTheory.Integral.IntervalIntegral.DerivIntegrable",
    "Mathlib.Analysis.SpecialFunctions.Integrals.Basic",
    "Mathlib.Probability.StrongLaw",
    "Mathlib.Probability.ProductMeasure",
    "Mathlib.Probability.Independence.InfinitePi",
    "Mathlib.MeasureTheory.Integral.Lebesgue.Basic",
    "Mathlib.MeasureTheory.Integral.Bochner.Basic",
    "Mathlib.Topology.MetricSpace.HausdorffDistance",
]

# The definitional closure of the five statements, in dependency order. Every constant the
# five compared types can reach, other than Lean core and Mathlib, is declared by one of
# these nodes; Comparator walks exactly this closure.
NODES = [
    "Curve",
    "Form1",
    "IsAdmissible",
    "massOfFunctional",
    "MetricCurrent1",
    "BoundaryZero",
    "curveCurrent",
    "curveMeasure",
    "morreyNorm",
    "IsGeodesicOn",
    "IsGeodesicResolution",
    "IsPiecewiseGeodesicWith",
    "IsPiecewiseGeodesic",
    "IsClosedCurve",
    "GeodesicPairing",
    "MassSupFormula",
    "ThetaL",
    "curveRestrict",
    "curveRestrictTot",
    "CurveMeasurableSpace",
    "PSFamily",
    "PaoliniStepanovExists",
    "psi",
]

# The five compared theorems, and how Solution.lean discharges each from the Tablet theorem
# of the same name in the root namespace.
NAMESPACE = "AtomicDecomposition"
STATEMENTS = [
    ("ApproximationMetric", "hAK hPS GP T hbdry ε hε0 hε1"),
    ("BBAssertion", "hAK hPS GP T hT0 hbdry"),
    ("SurgeryEta", "GP γ η hη0 hη1 hclosed hpg"),
    ("C1SmallBall", "γ k hpw"),
    ("EtaRepeats", "T F m hm Q ε C hε hC l hl"),
]

NODE_MARKER = re.compile(r"^-- \[TABLET NODE: .*\]$")
BODY_MARKER = "-- BODY"
GENERATED = "-- Generated by scripts/gen-surface.py from the Tablet node files. Do not edit."


def read_node(name):
    """Return (open lines, declaration text) for a Tablet node module.

    The declaration text starts at the node marker's docstring and runs to the end of the
    file, with the trellis `-- BODY` marker dropped. Imports are dropped: Challenge.lean
    supplies the Mathlib ones itself and must not reach any Tablet module. The `open` lines
    are kept and replayed around the declaration, because name resolution is part of what
    fixes the elaborated term.
    """
    path = TABLET / f"{name}.lean"
    lines = path.read_text().splitlines()
    marker = next(i for i, line in enumerate(lines) if NODE_MARKER.match(line))
    opens = [l for l in lines[:marker] if l.startswith("open ")]
    decl = [l for l in lines[marker + 1:] if l.strip() != BODY_MARKER]
    while decl and not decl[-1].strip():
        decl.pop()
    return opens, decl


def read_statement(name):
    """Return the signature of a Tablet theorem, character-identical to the source.

    The signature runs from the `theorem` line to the line before the `-- BODY` marker, which
    is the line ending `:= by`. That final `:= by` is returned separately so that Challenge
    can attach `sorry` and Solution can attach the Tablet theorem instead.
    """
    path = TABLET / f"{name}.lean"
    lines = path.read_text().splitlines()
    body = next(i for i, line in enumerate(lines) if line.strip() == BODY_MARKER)
    start = next(i for i in range(body) if lines[i].startswith(f"theorem {name} "))
    signature = lines[start:body]
    assert signature[-1].endswith(":= by"), f"{name}: unexpected signature tail"
    signature[-1] = signature[-1][: -len(":= by")].rstrip()
    return signature


def read_statement_doc(name):
    """The docstring to place above a compared theorem in Challenge.lean."""
    path = STATEMENT_DOCS / f"{name}.lean.in"
    if not path.exists():
        raise SystemExit(f"error: {path} is missing; every compared theorem needs a docstring"
                         " on the advertised surface")
    doc = path.read_text().rstrip().splitlines()
    if not doc[0].startswith("/--") or not doc[-1].rstrip().endswith("-/"):
        raise SystemExit(f"error: {path} is not a single Lean docstring block")
    return doc


def statement_opens():
    """The union of the `open` namespaces of the five theorem modules, in first-seen order.

    The five modules open overlapping sets, so the plain `open` lines are merged into one;
    opening the same union in one line resolves names exactly as the separate lines do.
    `open scoped` lines are kept as they are, since they are a different declaration.
    """
    plain, scoped = [], []
    for name, _ in STATEMENTS:
        for line in (TABLET / f"{name}.lean").read_text().splitlines():
            if line.startswith("open scoped "):
                if line not in scoped:
                    scoped.append(line)
            elif line.startswith("open "):
                for ns in line.removeprefix("open ").split():
                    if ns not in plain:
                        plain.append(ns)
    return ([f"open {' '.join(plain)}"] if plain else []) + scoped


def build_challenge():
    out = [GENERATED]
    out += [f"import {module}" for module in CHALLENGE_IMPORTS]
    out += ["", (ROOT / "scripts/challenge_header.lean.in").read_text().rstrip(), ""]

    for node in NODES:
        opens, decl = read_node(node)
        out.append("section")
        out += opens
        out.append("")
        out += decl
        out += ["end", ""]

    out += statement_opens()
    out += ["", f"namespace {NAMESPACE}", ""]
    for name, _ in STATEMENTS:
        out += read_statement_doc(name)
        out += read_statement(name)
        out += ["    := by", "  sorry", ""]
    out += [f"end {NAMESPACE}", ""]
    return "\n".join(out)


def build_solution():
    out = [GENERATED]
    out += [f"import Tablet.{name}" for name, _ in STATEMENTS]
    out += ["", (ROOT / "scripts/solution_header.lean.in").read_text().rstrip(), ""]
    out += statement_opens()
    out += ["", f"namespace {NAMESPACE}", ""]
    for name, args in STATEMENTS:
        out += read_statement(name)
        out += ["    :=", f"  _root_.{name} {args}", ""]
    out += [f"end {NAMESPACE}", ""]
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="verify the files are up to date instead of rewriting them")
    args = parser.parse_args()

    targets = {ROOT / "Challenge.lean": build_challenge(),
               ROOT / "Solution.lean": build_solution()}

    stale = []
    for path, content in targets.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.name)
        else:
            path.write_text(content)
            print(f"wrote {path.name} ({len(content.splitlines())} lines,"
                  f" {len(content.encode())} bytes)")

    if stale:
        print(f"error: {', '.join(stale)} no longer match the Tablet sources;"
              " run scripts/gen-surface.py", file=sys.stderr)
        return 1
    if args.check:
        print("Challenge.lean and Solution.lean match the Tablet sources")
    return 0


if __name__ == "__main__":
    sys.exit(main())
